version: "3.9"

services:
  postgres:
    image: postgres:16
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: hilltop_dev
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres_dev_data:/var/lib/postgresql/data
      - ./.data/postgres/config:/etc/postgresql
      - ./.data/postgres/log:/var/log/postgresql
    profiles:
      - postgres
      - stack

  mail:
    image: sj26/mailcatcher:latest
    ports:
      - "${MAILCATCHER_PORT}:1080"
      - "10250:1025"
    profiles:
      - mail

  reverse-proxy:
    image: nginx:alpine
    container_name: reverse-proxy
    volumes:
      - "./reverse-proxy.conf:/etc/nginx/conf.d/default.conf"
    ports:
      - "${API_PROXY_PORT}:${API_PROXY_PORT}"
    profiles:
      - proxy

volumes:
  postgres_dev_data: